######################################################################
# Automatically generated by qmake (3.0) ?? 10? 5 14:50:36 2023
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Change
INCLUDEPATH += .

# Input
SOURCES += main.cpp
