######################################################################
# Automatically generated by qmake (3.0) ?? 10? 5 14:18:57 2023
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Close
INCLUDEPATH += .

# Input
SOURCES += main.cpp
