######################################################################
# Automatically generated by qmake (3.0) ?? 10? 4 20:26:54 2023
######################################################################

QT += widgets
TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
