######################################################################
# Automatically generated by qmake (3.0) ?? 10? 5 22:44:02 2023
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Calculator2
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h ui_CalculatorDialog.h
FORMS += CalculatorDialog.ui
SOURCES += CalculatorDialog.cpp main.cpp
