######################################################################
# Automatically generated by qmake (3.0) ?? 10? 5 18:26:25 2023
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Calculator
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h
SOURCES += CalculatorDialog.cpp main.cpp
