######################################################################
# Automatically generated by qmake (3.0) ?? 10? 4 19:21:55 2023
######################################################################

QT += widgets
TEMPLATE = app
TARGET = qtslider
INCLUDEPATH += .

# Input
SOURCES += slider.cpp
