######################################################################
# Automatically generated by qmake (3.0) ?? 10? 5 19:33:25 2023
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Time
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h
SOURCES += main.cpp TimeDialog.cpp
