######################################################################
# Automatically generated by qmake (3.0) ?? 10? 4 20:36:05 2023
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Button
INCLUDEPATH += .

# Input
SOURCES += main.cpp
