######################################################################
# Automatically generated by qmake (3.0) ?? 10? 6 10:43:13 2023
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Login
INCLUDEPATH += .

# Input
HEADERS += LoginDialog.h ui_LoginDialog.h
FORMS += LoginDialog.ui
SOURCES += LoginDialog.cpp main.cpp
