######################################################################
# Automatically generated by qmake (3.0) ?? 10? 4 21:00:14 2023
######################################################################

QT += widgets
TEMPLATE = app
TARGET = parent
INCLUDEPATH += .

# Input
SOURCES += main.cpp
